language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_USER
    - secure: "SbpFKMOEwSWjNFki1MphkBjtuBGZLh72HoWAvNdP2gZmH6KY5X9acimg7DoMiUaIPX9iHo4lhwszHezvVcmcXwT8Rc/v/291OZTWTeovNL6SfucsaHygXgGetNGiOX/OxeS059kWh33u+WPyLmG1DubhYDwuNu7cmX7biLZmJEdXYo0iQKbN4lqqIzIu9akLp9E3SZXmV4rCfsSXB9HncWqisMMao/K9l1/kUnvPj7nku9tImrB18Ct/PADmPrFz+h1v9ORrrHWCYWLXDyXa4Xln7ahjrOoCKpbobvFCQFp3F4kTGC8HcfrtXZlPvL32CnLXSEi9HwQWKRvpOnAkEvlIxG/Hcyxjxr8skPmERm3s5vvsta8iby4QcxF6rr4bCpqnoS3b8aeeSCEKomTdpYFMq/uEHIbMoBm3WMve0rJSu9GvSG/wPcncM2EVZips0iPn7tDsny/D0CIYLXDGlCjIZBSUNMCyXswA8kc8IqQFMxxd//lzr3j3V8unykvAtyOm1kygn6TwPo6vN2ZG6s+H5REDP7yxco9OJdS2qgIQ6aIpFuV7H3JwuecwwoHkDSeUpyjW7TRWOiJspc2tXAyJkH8iujdpzQ2w+BZuj41TShFW9LuLWp5Em5Hs/ONTLBkgvBdq7M2B/ewBK7pkbot9aOxCFy3hF5iv1uMgQJw="
    # DEPLOY_HOST
    - secure: "k84IT+DxBe/fPoY/dbl+W7gAFiunZE4a2m2ioC0Z3hh6RweWzJtj/N+2GQud1iSasCbOnYnT/w3VVgJuo+zHCSFjwpBBkVih4GlsLjrwgl6YFxKdZCtGx0KX3R1yj9adPAuRQJ09vEE2I1ug6S+vyhghF6envZQCEXabVKmzZ6YBJZkn1LrMhrwN1flFdQa0dYI5M0E+bzzhnFmzGSVPe9QCX1vqIvMUto1XRCovc4ei+DedAqC0Rev384w3iGyiOnd67MaTnHy5pDVKTZu5feiT/aPNof7o8DoGXTfCg7vZc8T3e5C6PXF8U3EAs+7KfBsEwF/t17cT6sosckdyxK3UtT7U4+Utsblx1ki11qFWyBHadp6hPCXDvs/wFN/pUINRzjv/ko1xJ1mQQs+vnV3uB/ZvnbXTjb2hl8ao4QlKDPa2pmlp+2KTJyjincklwDEbdtQXh5weiOl7rtJtqKao86a4sVlU6kwXKcvvGasLuem1YPofoYhdA49FeyGHr9+pK6JbBSWX4QtLzGn18kwxqNwxlXYXP/FRmS+7zbT7+az9qlQfjdcVvmffkFmkqJwFBjmEmaaQEpWo8EuFLAwAB0f3+Q3LjVmEkWWjW0yLwkZB96q+wOrscobzXcPVTSknqHHEpvcq5SO6iDk9llkWdcZo1bmanvhykj2uvKg="

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
    - liri-wayland-artifacts.tar.gz
    - fluid-artifacts.tar.gz
    - libliri-artifacts.tar.gz
    - qtgsettings-artifacts.tar.gz
  packages:
    - qbs
    - qt5-quickcontrols2
    - qt5-wayland
    - qt5-tools
    - polkit-qt5
    - libqtxdg
    - glib2
    - xkeyboard-config
    - xorg-server-xvfb
    #- clazy-git
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - eval `dbus-launch --sh-syntax` && xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) profile:qt5

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
